---
- name: add apt-key
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present
  become_method: sudo
  become: yes
  become_user: root

- name: add repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
  become_method: sudo
  become: yes
  become_user: root

- name: install postgresql
  apt: 
    name: "python-psycopg2,postgresql-{{ postgresql_version }}"
    state: present
    update_cache: yes
  become_method: sudo
  become: yes
  become_user: root

