---

- include_vars: "{{ansible_distribution}}.yml"

- name: Install dependencies
  apt: 
    name: python-pycurl
  become_method: sudo
  become: yes
  become_user: root

- name: Add nginx repository
  apt_repository: 
    repo: ppa:nginx/stable
  when: nginx_apt_use_ppa_repo and ansible_distribution == "Ubuntu"
  become_method: sudo
  become: yes
  become_user: root

- name: Install Dependencies
  apt: 
    name: "{{ item }}"
  with_items: 
    - nginx
    - python-passlib 
  become_method: sudo
  become: yes
  become_user: root

