---
- name: create AWS S3 buckets
  s3:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    bucket: "{{ item }}"
    mode: create
    region: "{{ region }}"
  with_items: "{{ s3buckets }}"
