#!/bin/sh

# This file was generated by ansible
# Do NOT modify this file!

{% set app = item -%}
{% set run_dir = item.run_dir|default("/home/django/%s/run" % item.name) -%}
{% set log_dir = item.log_dir|default("/home/django/%s/log" % item.name) -%}
{% set etc_dir = item.etc_dir|default("/home/django/%s/etc" % item.name) -%}
{% set env_dir = item.virtualenv|default("/home/django/%s/env" % item.name) -%}
{% set app_dir = item.app_dir|default("/home/django/%s/src" % item.name) -%}
{% set pip = (env_dir + '/bin/pip') if env_dir else 'pip' -%}
{% set pip_packages = item.get('pip_packages', wsgi_pip_packages) -%}
{% set pip_requirements = item.get('pip_requirements') -%}

[ -d {{app_dir}} ] || {
    echo "Application directory is not found. Exiting. "
    exit 0
}

cd {{app_dir}}

{% if env_dir -%}
[ -d {{env_dir}} ] || virtualenv {{env_dir}} -p {{app.get('virtualenv_python', wsgi_virtualenv_python)}}
{% endif %}

# Instal WSGI Server
{{pip}} install {{item.get('server', wsgi_server)}}

{% for package in pip_packages %}
{{pip}} install {{package}}
{% endfor %}

{% if pip_requirements %}
# Install requiremrents
{{pip}} install -r {{pip_requirements}}
{% endif %}
