---
- name: wsgi restart
  service: name={{item.name}}-wsgi state=restarted
  with_items: "{{wsgi_applications}}"
  become_method: sudo
  become: yes
  become_user: root

- name: wsgi reload
  service: name={{item.name}}-wsgi state=reloaded
  with_items: "{{wsgi_applications}}"
  become_method: sudo
  become: yes
  become_user: root
