---

- name: ensure the source user exist
  user:
    name: "{{ source_user }}"
    createhome: yes

- name: ensure the source group exist
  group:
    name: "{{ source_group }}"

- name: ensure user ssh home exists
  file:
    state: directory
    path: "{{ source_user_ssh_home }}"
    owner: "{{ source_user }}"
    recurse: yes

- name: copy ssh keys from files
  copy: 
    src: "{{ item }}"
    dest: "{{ source_user_ssh_home }}/{{ item.split('/')[-1] }}"
    mode: 0400
    owner: "{{ source_user }}"
  with_items: "{{source_copy_keys}}"

- name: copy ssh keys from variables
  template:
    src: ssh.j2
    dest: "{{source_user_ssh_home}}/{{ item.file_name | default('id_rsa') }}"
    owner: "{{ source_user }}"
    mode: 0400
  with_items: "{{source_ssh_keys}}"

- name: setup ssh hosts
  lineinfile: 
    line: "{{ item }}"
    insertafter: "EOF"
    state: "present"
    create: "yes"
    mode: 0644
    dest: "{{ source_user_ssh_home }}/known_hosts"
    owner: "{{ source_user }}"
  with_items: "{{ source_fingerprints }}"

- name: ensure source directory exists
  file: 
    state: directory
    path: "{{ item.dest }}"
    owner: "{{ source_user }}"
    recurse: yes
  with_items: "{{source_sources}}"

