---
- name: run django manage commands
  django_manage:
    command: "{{ item }}"
    app_path: "{{ django_app_dir }}"
    settings: "{{ django_settings_module }}"
    virtualenv: "{{ django_env_dir }}"
  changed_when: False
  become_method: sudo
  become: yes
  become_user: "{{django_user}}"
  with_items: django_manage_list
  ignore_errors: django_ignore_errors
