---

- include_vars: "{{ansible_distribution}}.yml"

- name: Install dependencies
  apt: name={{item}}
  with_items:
  - cron
  - gzip
  - python-boto
  - s3cmd
  become_method: sudo
  become: yes
  become_user: root

- set_fact: backup_duplicity_pkg="{{backup_duplicity_pkg}}={{backup_duplicity_version}}"
  when: backup_duplicity_version

- name: Install duplicity
  apt: pkg={{backup_duplicity_pkg}}
  become_method: sudo
  become: yes
  become_user: root
